import { Router } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { getDb, nowIso } from '../db/database.js';
import { signAccessToken, requireAuth } from '../middleware/auth.js';
import { writeAudit } from '../db/audit.js';
import { getRefreshTokenDays, serverConfig } from '../utils/config.js';
import { validateBody } from '../middleware/validate-request.js';
export const authRouter = Router();
const loginSchema=z.object({username:z.string().trim().min(1).max(120),password:z.string().min(1).max(200)});
const logoutSchema=z.object({refreshToken:z.string().trim().min(20).max(300).optional()}).passthrough();
function publicUser(user){ return {id:user.id,username:user.username,email:user.email,displayName:user.display_name,role:user.role}; }
function hashToken(token){ return crypto.createHash('sha256').update(token).digest('hex'); }
function isLocked(user){ return user?.locked_until && new Date(user.locked_until).getTime() > Date.now(); }
function loginEvent({user=null,username,success,failureReason=null,req}){ getDb().prepare(`INSERT INTO login_events (id,user_id,username,success,failure_reason,ip_address,user_agent,created_at) VALUES (?,?,?,?,?,?,?,?)`).run(nanoid(),user?.id||null,String(username||'').slice(0,120),success?1:0,failureReason,req?.ip||null,req?.headers?.['user-agent']||null,nowIso()); }
function registerFailure(user,username,reason,req){ loginEvent({user,username,success:false,failureReason:reason,req}); if(user?.id){ const failed=Number(user.failed_login_count||0)+1; const lockedUntil=failed>=serverConfig.loginRateLimitMax ? new Date(Date.now()+15*60*1000).toISOString() : null; getDb().prepare('UPDATE users SET failed_login_count=?, locked_until=COALESCE(?, locked_until), updated_at=? WHERE id=?').run(failed,lockedUntil,nowIso(),user.id); writeAudit({userId:user.id,action:lockedUntil?'auth.account_locked':'auth.login_failed',entityType:'user',entityId:user.id,newValue:{reason,failedLoginCount:failed,lockedUntil},req,severity:lockedUntil?'warn':'info'}); } else writeAudit({action:'auth.login_failed_unknown_user',entityType:'user',newValue:{username,reason},req,severity:'info'}); }
function createRefreshToken(userId){ const token=crypto.randomBytes(48).toString('hex'); const days=getRefreshTokenDays(); const expiresAt=new Date(Date.now()+days*86400000).toISOString(); getDb().prepare(`INSERT INTO refresh_tokens (id,user_id,token_hash,expires_at,created_at) VALUES (?,?,?,?,?)`).run(nanoid(),userId,hashToken(token),expiresAt,nowIso()); return {token,expiresAt}; }
function assertPasswordPolicy(password){ const p=String(password||''); const min=serverConfig.passwordMinLength; if(p.length<min) throw Object.assign(new Error(`Mot de passe trop court (minimum ${min} caractères)`),{status:400}); if(!/[A-Z]/.test(p)||!/[a-z]/.test(p)||!/[0-9]/.test(p)) throw Object.assign(new Error('Mot de passe insuffisamment complexe'),{status:400}); }
export { assertPasswordPolicy };
authRouter.post('/login', validateBody(loginSchema), async (req,res,next)=>{ try{ const body=req.body; const user=getDb().prepare('SELECT * FROM users WHERE username = ? OR email = ?').get(body.username,body.username); if(!user){ registerFailure(null,body.username,'unknown_user',req); return res.status(401).json({error:'Identifiants invalides'}); } if(Number(user.is_active)!==1){ registerFailure(user,body.username,'inactive_account',req); return res.status(401).json({error:'Identifiants invalides'}); } if(isLocked(user)){ loginEvent({user,username:body.username,success:false,failureReason:'locked',req}); writeAudit({userId:user.id,action:'auth.login_blocked_locked',entityType:'user',entityId:user.id,newValue:{lockedUntil:user.locked_until},req,severity:'warn'}); return res.status(423).json({error:'Compte temporairement verrouillé'}); } const ok=await bcrypt.compare(body.password,user.password_hash); if(!ok){ registerFailure(user,body.username,'bad_password',req); return res.status(401).json({error:'Identifiants invalides'}); } loginEvent({user,username:body.username,success:true,req}); getDb().prepare('UPDATE users SET last_login_at = ?, failed_login_count=0, locked_until=NULL, updated_at = ? WHERE id = ?').run(nowIso(),nowIso(),user.id); const refreshed=getDb().prepare('SELECT id, username, email, display_name, role, password_changed_at FROM users WHERE id = ?').get(user.id); const accessToken=signAccessToken(refreshed); const refresh=createRefreshToken(user.id); writeAudit({userId:user.id,action:'auth.login',entityType:'user',entityId:user.id,req}); res.json({accessToken,refreshToken:refresh.token,refreshTokenExpiresAt:refresh.expiresAt,user:publicUser(refreshed)}); } catch(err){ next(err); } });
authRouter.post('/logout', requireAuth, validateBody(logoutSchema), async (req,res,next)=>{ try{ const refreshToken=req.body?.refreshToken; if(refreshToken) getDb().prepare('UPDATE refresh_tokens SET revoked_at = ? WHERE token_hash = ? AND revoked_at IS NULL').run(nowIso(),hashToken(refreshToken)); writeAudit({userId:req.user.id,action:'auth.logout',entityType:'user',entityId:req.user.id,req}); res.json({ok:true}); } catch(err){ next(err); } });
authRouter.get('/me', requireAuth, (req,res)=>res.json({user:publicUser(req.user)}));
