(function(window){
  'use strict';
  const root=window.DLCreatorCore=window.DLCreatorCore||{};
  const ROLE_ORDER=['lecteur','redacteur','validateur','responsableDomaine','chefFormation','admin'];
  const ROLE_LABELS=Object.freeze({admin:'Admin',chefFormation:'Chef formation',responsableDomaine:'Responsable domaine',validateur:'Validateur',redacteur:'Rédacteur',lecteur:'Lecteur'});
  const PERMISSIONS=Object.freeze({
    admin:['app:admin','users:manage','users:disable','users:import','users:export','permissions:manage','workflow:transition','workflow:comment','workflow:validate','workflow:validate:domain','workflow:validate:chief','workflow:publish:distributed','workflow:refuse','workflow:block-publication','dl:create','dl:read','dl:read:restricted','dl:update','dl:delete','dl:validate','dl:publish','dl:publish:distributed','dl:archive','dl:ownership:transfer','dl:conflict:resolve','audit:read','audit:export','audit:purge','backup:manage','diagnostics:read','supervision:read','settings:manage','share:export'],
    chefFormation:['app:admin','users:manage','users:disable','users:import','users:export','permissions:manage','workflow:transition','workflow:comment','workflow:validate','workflow:validate:domain','workflow:validate:chief','workflow:publish:distributed','workflow:refuse','workflow:block-publication','dl:create','dl:read','dl:read:restricted','dl:update','dl:delete','dl:validate','dl:publish','dl:publish:distributed','dl:archive','dl:ownership:transfer','dl:conflict:resolve','audit:read','audit:export','audit:purge','backup:manage','diagnostics:read','supervision:read','settings:manage','share:export'],
    responsableDomaine:['workflow:transition','workflow:comment','workflow:validate','workflow:validate:domain','workflow:refuse','workflow:block-publication','dl:create','dl:read','dl:update','dl:validate','dl:publish','dl:archive','dl:ownership:transfer','dl:conflict:resolve','audit:read','diagnostics:read','supervision:read','share:export'],
    validateur:['workflow:comment','workflow:validate','workflow:refuse','dl:read','dl:read:restricted','dl:validate','audit:read'],
    redacteur:['workflow:comment','dl:create','dl:read','dl:update','share:export'],
    lecteur:['dl:read']
  });
  const MODULE_PERMISSIONS=Object.freeze({utilisateurs:['users:manage','users:disable','users:import','users:export'],workflow:['workflow:transition','workflow:comment','workflow:validate','workflow:validate:domain','workflow:validate:chief'],publication:['dl:publish','workflow:publish:distributed'],archivage:['dl:archive'],audit:['audit:read','audit:export'],backup:['backup:manage'],diagnostics:['diagnostics:read'],documents:['dl:create','dl:read','dl:update','dl:delete'],partage:['share:export'],ownership:['dl:ownership:transfer'],conflits:['dl:conflict:resolve'],supervision:['supervision:read']});
  const LEGACY=Object.freeze({'ADMIN STRUCTURE APPLICATION':'admin','GESTION DL':'chefFormation','VALIDATION DL':'validateur','RÉDACTION DL':'redacteur','REDACTION DL':'redacteur','CONSULTATION DL':'lecteur'});
  function normalizeRole(value){const raw=String(value||'lecteur').trim();const mapped=LEGACY[raw.toUpperCase()]||raw;return ROLE_ORDER.includes(mapped)?mapped:'lecteur';}
  function permissionsFor(role){const r=normalizeRole(role);const idx=ROLE_ORDER.indexOf(r);const merged=new Set();ROLE_ORDER.slice(0,Math.max(idx+1,1)).forEach(x=>(PERMISSIONS[x]||[]).forEach(p=>merged.add(p)));return Array.from(merged).sort();}
  function currentUser(){try{return root.authClient?.getCurrentUser?.()||root.authState?.read?.().userProfile||root.authState?.read?.().user||root.pilotUsersService?.list?.()[0]||root.userService?.list?.()[0]||{};}catch{return {};}}
  function roleOf(user){if(Array.isArray(user?.roles)&&user.roles.length){return normalizeRole(user.roles[user.roles.length-1]);}return normalizeRole(user?.primaryRole||user?.role||user?.droitAcces||user?.fonction||user?.function||'lecteur');}
  function effectivePermissions(user){const u=user||currentUser();const roles=Array.isArray(u?.roles)&&u.roles.length?u.roles:[roleOf(u)];const merged=new Set();roles.forEach(r=>permissionsFor(r).forEach(p=>merged.add(p)));(Array.isArray(u?.permissions)?u.permissions:[]).forEach(p=>merged.add(p));return Array.from(merged).sort();}
  function domainAllowed(doc,user){const domain=String(doc?.workflow?.domain||doc?.identification?.domaine||doc?.domaine||'').trim();const userDomain=String(user?.domain||user?.domaine||'Tous domaines').trim();return !domain||!userDomain||userDomain==='Tous domaines'||domain.toLowerCase()===userDomain.toLowerCase();}
  function can(permission,user,context){const u=user||currentUser();if(u?.overrideAdmin===true)return true;const allowed=effectivePermissions(u).includes(permission)&&(!context?.document||domainAllowed(context.document,u));if(!allowed){root.auditService?.write?.('permission-refusée-détaillée',{permission,userId:u?.id||'',role:roleOf(u),domain:u?.domain||'',reason:context?.document&&!domainAllowed(context.document,u)?'restriction domaine':'permission absente'},'SECURITY');}return allowed;}
  function canModule(module,user){return (MODULE_PERMISSIONS[module]||[]).some(p=>can(p,user));}
  function matrix(){return ROLE_ORDER.map(role=>({role,label:ROLE_LABELS[role],permissions:permissionsFor(role)}));}
  function diagnostic(user){const u=user||currentUser();const role=roleOf(u);return{schema:'dl.creator.rbac.diagnostic.v3',role,label:ROLE_LABELS[role]||role,roles:Array.isArray(u?.roles)?u.roles:[role],domain:u?.domain||'Tous domaines',permissions:effectivePermissions(u),modules:MODULE_PERMISSIONS,matrix:matrix(),overrideAdmin:u?.overrideAdmin===true,serverPermissionsPrepared:true,serverPermissionsEnabled:false,auditable:true,domainRestrictionsPrepared:true,publicationRestrictionsPrepared:true,archiveRestrictionsPrepared:true,ownershipPermissionsPrepared:true,conflictPermissionsPrepared:true,supervisionPermissionsPrepared:true,restrictionsActive:effectivePermissions(u).length<effectivePermissions({roles:['admin']}).length};}
  root.rbacService={chefFormationAdminEquivalent:true,roles:ROLE_LABELS,roleOrder:ROLE_ORDER,permissionsByRole:PERMISSIONS,modulePermissions:MODULE_PERMISSIONS,normalizeRole,permissionsFor,effectivePermissions,roleOf,domainAllowed,can,canModule,matrix,diagnostic};
})(window);
