(function(window){
  'use strict';
  /** Feature flags publics. Aucun secret, aucun token, aucun hash sensible. */
  window.DL_CREATOR_FEATURE_FLAGS = Object.freeze({
    offlineFirst: true,
    backendPrepared: true,
    backendEnabled: false,
    remoteStorageEnabled: false,
    serverAuthEnabled: false,
    serverAuditEnabled: false,
    transactionalMailEnabled: false,
    syncQueuePrepared: true,
    syncRemoteEnabledByDefault: false,
    backupRestorePrepared: true,
    rbacCentralized: true,
    pdfEngineLocked: true,
    githubSecurityReadyV910: true,
    runtimeConfigExternalizedV910: true,
    frontendSecretsRemovedV910: true,
    envArchitecturePreparedV910: true,
    netlifyPreviewHardenedV910: true,
    githubPrivateReadyV910: true,
    configCentralizationV910: true,
    libraryJsonImportV912: true,
    safariSessionResumeGuardV912: true,
    accessEmailPreviewBoldTitlesV912: true,
    filRougeUiAddSectionBottomV912: true,
    filRougeIconsAlignmentV913: true,
    filRougeSectionImagesV1000: true,
    filRougeImageGalleryPdfV1000: true,
    filRougeImagesDragDropDirectV1001: true,
    filRougeImagesCrop43V1001: true,
    filRougeImagesDeleteConfirmV1001: true,
    filRougeImagesPdfSpacingFixedV1001: true,
    filRougeImagesPdfTitleAlignV1002: true,
    publicCiblePdfBoldCaseV1002: true,
    publicCiblePdfBoldBlack11V1003: true,
    filRougeImageReorderV1004: true,
    publicCiblePdfBoldBlack10V1004: true,
    validationStatusPreservedOnImportV1004: true,
    filRougeImageCaptionGreyLeftV1002: true,
    filRougeImageCaptionSentenceCaseV1002: true
  });
})(window);
