(function(window){
  'use strict';
  const root = window.DLCreatorCore = window.DLCreatorCore || {};
  const runtime = window.DL_CREATOR_RUNTIME_CONFIG || {};
  const runtimeFlags = window.DL_CREATOR_FEATURE_FLAGS || {};
  const versionInfo = Object.freeze({
    version: runtime.version || 'v10.03',
    numericVersion: runtime.numericVersion || '10.03',
    build: runtime.build || '2026.05.12-v10.03-pdf-public-cible-bold-black-11pt',
    buildIncrement: runtime.buildIncrement || 203,
    buildDate: runtime.buildDate || '2026-05-12',
    buildDateUTC: new Date(runtime.buildDateUTC || '2026-05-12T07:30:00Z').toISOString(),
    environment: runtime.environment || 'local',
    supportedEnvironments: Object.freeze(['local','pilote','preview','production']),
    productionMode: runtime.productionMode || 'pilote',
    apiVersion: runtime.apiVersion || '2026-05-pilot-v7',
    minimumCompatibleVersion: runtime.minimumCompatibleVersion || 'v8.10',
    compatibility: Object.freeze({
      minSchema: 'dl.creator.web.v2',
      legacyDL: true,
      safari: true,
      chrome: true,
      offlineFirst: true,
      netlifyFunctions: true,
      githubActions: true,
      progressiveSyncPrepared: true,
      distributedValidationPrepared: true,
      conflictDetectionPrepared: true,
      pilotMultiProfilesPrepared: true
    }),
    flags: Object.freeze({
      offlineFirst: true,
      backendPrepared: true,
      backendEnabled: false,
      remoteStorageEnabled: false,
      serverAuthEnabled: false,
      serverAuditEnabled: false,
      transactionalMailEnabled: false,
      syncQueuePrepared: true,
      syncRemoteEnabledByDefault: false,
      backupRestorePrepared: true,
      rbacCentralized: true,
      privacyScreenPrepared: true,
      pilotDiagnosticsReady: true,
      diagnosticProductionV4: true,
      migrationJournalEnabled: true,
      auditRotationHardened: true,
      permissionDenialAuditEnabled: true,
      objectivesFalsePositiveFixed: true,
      pdfEngineLocked: true,
      generalitesVersionPersistenceFixed: true,
      referenceVersionSyncFixed: true,
      validationStatusMirrorFixed: true,
      validationTransmitAutoStatusFixed: true,
      generalitesStatusComputedStyleFixed: true,
      validationButtonsCentralStatusFixed: true,
      validationManualStatusMirrorFixed: true,
      planLessonTrainerPropagationFixed: true,
      planTrainerAutocompletePartialInputFixed: true,
      planTrainerManualOverridePreserved: true,
      planTrainerManualInputPersistentFixed: true,
      minorCorrectiveHeaderVersioning: true,
      libraryUpgradePersistenceHardened: true,
      distributedValidationEnabled: true,
      remoteValidationEnabled: false,
      collaborativeLocksPrepared: true,
      conflictDetectionPrepared: true,
      multiTabOptimisticLockHardened: true,
      preproductionGithubNetlify: true,
      netlifyFunctionsPreparedV890: true,
      transactionalMailPreparedV890: true,
      backupZipPreparedV890: true,
      supervisionPilotPreparedV890: true,
      workflowAdvancedPreparedV890: true,
      serverAuditPreparedV890: true,
      environmentBannerPrepared: true,
      netlifyFunctionsPreparedV900: true,
      netlifyFunctionsDiagnosticV900: true,
      serverApiSafeWrapperV900: true,
      transactionalMailPreparedV900: true,
      notificationJournalPreparedV900: true,
      backupDiagnosticsV900: true,
      bootGuardReferencesV900: true,
      gestionAccesPathSafeV901: true,
      personnelCsvAutocompleteV901: true,
      habilitationEmailPersistenceV901: true,
      chefFormationAdminStructureV901: true,
      functionsLocalStaticFallbackV902: true,
      gestionAccesVisibleInputV902: true,
      gestionAccesPersonnelAutocompleteAlignedV902: true,
      nipLoginPreparedV902: true,
      profileAccessConsistencyV902: true,
      accessEmailNipTemplateV902: true,
      mesDLReadOnlyModeV902: true,
      mesDLExportPdfV902: true,
      keywordsSearchMin3V902: true,
      archiveDLFixedV902: true,
      importJsonClarifiedV902: true,
      gestionAccesResponsableEngineAlignedV903: true,
      gestionAccesExplicitSaveV903: true,
      secureActivationFlowPreparedV903: true,
      activationEmailVerificationPreparedV903: true,
      lastAccessEmailTraceV903: true,
      planHoraireResponsive4SessionsV903: true,
      keywordsFocusPreservedV903: true,
      profileEmailBidirectionalSyncV903: true,
      leaveDLWarningV903: true,
      githubRepositoryReadyV904: true,
      netlifyPreviewReadyV904: true,
      saveHabilitationsExplicitFixedV904: true,
      accessRightsRecoveryHardenedV904: true,
      storageQuotaGuardV904: true,
      githubDocsReadyV904: true,
      githubSecurityReadyV910: !!runtimeFlags.githubSecurityReadyV910,
      runtimeConfigExternalizedV910: !!runtimeFlags.runtimeConfigExternalizedV910,
      frontendSecretsRemovedV910: !!runtimeFlags.frontendSecretsRemovedV910,
      envArchitecturePreparedV910: !!runtimeFlags.envArchitecturePreparedV910,
      netlifyPreviewHardenedV910: !!runtimeFlags.netlifyPreviewHardenedV910,
      githubPrivateReadyV910: !!runtimeFlags.githubPrivateReadyV910,
      configCentralizationV910: !!runtimeFlags.configCentralizationV910,
      libraryJsonImportV912: true,
      safariSessionResumeGuardV912: true,
      accessEmailPreviewBoldTitlesV912: true,
      filRougeUiAddSectionBottomV912: true,
    filRougeIconsAlignmentV913: true,
      filRougeSectionImagesV1000: true,
      filRougeImageGalleryPdfV1000: true,
      filRougeImagesDragDropDirectV1001: true,
      filRougeImagesCrop43V1001: true,
      filRougeImagesDeleteConfirmV1001: true,
      filRougeImagesPdfSpacingFixedV1001: true,
    filRougeImagesPdfTitleAlignV1002: true,
    publicCiblePdfBoldCaseV1002: true,
    publicCiblePdfBoldBlack11V1003: true,
    filRougeImageCaptionGreyLeftV1002: true,
    filRougeImageCaptionSentenceCaseV1002: true
    })
  });
  root.versionInfo = versionInfo;
  root.getVersionInfo = function(){ return versionInfo; };
})(window);
