import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import { authRouter } from './routes/auth.js';
import { dlRouter } from './routes/dl.js';
import { libraryRouter } from './routes/library.js';
import { adminRouter } from './routes/admin.js';
import { adminDashboardRouter } from './routes/admin-dashboard.js';
import { notificationsRouter } from './routes/notifications.js';
import { workflowRouter } from './routes/workflow.js';
import { errorHandler, notFound } from './middleware/error-handler.js';
import { migrate } from './db/database.js';
import { getJwtSecret, getPort, getCorsOrigin, serverConfig } from './utils/config.js';
import { logger, requestIdMiddleware } from './services/logger.js';
getJwtSecret(); migrate();
const app=express(); const port=getPort();
app.disable('x-powered-by'); if(serverConfig.trustProxy) app.set('trust proxy',1);
app.use(requestIdMiddleware);
app.use(helmet({ crossOriginResourcePolicy:{policy:'same-site'}, contentSecurityPolicy:serverConfig.isProd ? undefined : false }));
app.use(cors({ origin:getCorsOrigin(), credentials:true }));
app.use(express.json({ limit:serverConfig.jsonLimit, strict:true }));
app.use(rateLimit({ windowMs:serverConfig.rateLimitWindowMs, limit:serverConfig.rateLimitMax, standardHeaders:true, legacyHeaders:false }));
app.use('/api/auth/login', rateLimit({ windowMs:serverConfig.rateLimitWindowMs, limit:serverConfig.loginRateLimitMax, standardHeaders:true, legacyHeaders:false }));
app.get('/api/health', (_req,res)=>res.json({ ok:true, service:'dl-creator-web-server', phase:'8', environment:process.env.NODE_ENV||'development', time:new Date().toISOString() }));
app.use('/api/auth',authRouter); app.use('/api/dl',dlRouter); app.use('/api/dl',workflowRouter); app.use('/api/library',libraryRouter); app.use('/api/admin/dashboard',adminDashboardRouter); app.use('/api/admin/notifications',notificationsRouter); app.use('/api/admin',adminRouter); app.use(notFound); app.use(errorHandler);
app.listen(port,()=>logger.info('DL Creator Web server listening',{phase:'8',port,environment:process.env.NODE_ENV||'development'}));
